import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" data-theme="blue">
      <body className={` antialiased`}>
        <div className="bg-background text-foreground p-6">
          
          <h1 className={`font-nanum-gothic text-2xl font-black`}>
            나눔고딕  Tailwind 4.0에서 @theme 적용
          </h1>

          <p className={`text-2xl font-bold  `}>
          Noto Sans KR 은 1순위 기본 폰트 설정 완료!
          </p>
        </div>

        {children}
      </body>
    </html>
  );
}
